version: "3.7"

services:
  order_service:
    build:
      context: .
      dockerfile: OrderService.Dockerfile
    volumes:
      - ./:/home/node/app/
    container_name: order_service
    expose:
      - "4000"
      - "8090"
    ports:
      - "4000:4000"
    command: npm run order_service
    extra_hosts:
      - "host.docker.internal:host-gateway"