name: Node.js CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - run: npm ci
        working-directory: src
      - run: npm run build --if-present
        working-directory: src
      - run: npm test
        working-directory: src
        env:
          DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
